### ISSUE TITLE
能否创建`LICENSE`文件？

### ISSUE THREAD

**Issue by YDX-2147483647** [Z-Luan/BIT-AI#1]
现在已经明确采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)，但 GitHub 没办法识别。请问能否创建`LICENSE`文件呢？

https://github.com/Z-Luan/BIT-AI/blob/ed0213f4d764ccd60fa8dc20f4adc7569ce58383/README.md?plain=1#L50-L53

大约不是很困难：在 GitHub 网页上创建文件，文件名填`LICENSE`，会出现`Choose a license template`，然后能直接选。具体可以参考 [Adding a license to a repository - GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)。

**Comment by Z-Luan** [comment]
感谢建议 已创建
